name: "dune test"

on: 
  pull_request:
      branches:
        - "main"
      paths:
        - "weir/**"

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: weir
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3.7.1
        with:
          ocaml-compiler: "5.4"
          dune-cache: true
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune test
