name: "dune test"

on: 
    push:
        branches:
            - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: parser
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2
      - run: opam install . --deps-only
      - run: opam exec -- dune test